export default {
  friends: {
    baseCost: 5,
    baseProfit: 1,
    upgrades: new Map([
      [1, { title: 'gaming/idrupgrade:FRIENDS_1_TITLE', response: 'gaming/idrupgrade:FRIENDS_1_RESPONSE' }],
      [25, { title: 'gaming/idrupgrade:FRIENDS_2_TITLE', response: 'gaming/idrupgrade:FRIENDS_2_RESPONSE' }],
      [50, { title: 'gaming/idrupgrade:FRIENDS_3_TITLE', response: 'gaming/idrupgrade:FRIENDS_3_RESPONSE' }],
      [75, { title: 'gaming/idrupgrade:FRIENDS_4_TITLE', response: 'gaming/idrupgrade:FRIENDS_4_RESPONSE' }],
      [100, { title: 'gaming/idrupgrade:FRIENDS_5_TITLE', response: 'gaming/idrupgrade:FRIENDS_5_RESPONSE' }],
      [150, { title: 'gaming/idrupgrade:FRIENDS_6_TITLE', response: 'gaming/idrupgrade:FRIENDS_6_RESPONSE' }],
      [200, { title: 'gaming/idrupgrade:FRIENDS_7_TITLE', response: 'gaming/idrupgrade:FRIENDS_7_RESPONSE' }],
      [300, { title: 'gaming/idrupgrade:FRIENDS_8_TITLE', response: 'gaming/idrupgrade:FRIENDS_8_RESPONSE' }],
      [400, { title: 'gaming/idrupgrade:FRIENDS_9_TITLE', response: 'gaming/idrupgrade:FRIENDS_9_RESPONSE' }],
      [500, { title: 'gaming/idrupgrade:FRIENDS_10_TITLE', response: 'gaming/idrupgrade:FRIENDS_10_RESPONSE' }],
      [600, { title: 'gaming/idrupgrade:FRIENDS_11_TITLE', response: 'gaming/idrupgrade:FRIENDS_11_RESPONSE' }],
      [700, { title: 'gaming/idrupgrade:FRIENDS_12_TITLE', response: 'gaming/idrupgrade:FRIENDS_12_RESPONSE' }],
      [800, { title: 'gaming/idrupgrade:FRIENDS_13_TITLE', response: 'gaming/idrupgrade:FRIENDS_13_RESPONSE' }],
      [900, { title: 'gaming/idrupgrade:FRIENDS_14_TITLE', response: 'gaming/idrupgrade:FRIENDS_14_RESPONSE' }],
      [1000, { title: 'gaming/idrupgrade:FRIENDS_15_TITLE', response: 'gaming/idrupgrade:FRIENDS_15_RESPONSE' }],
      [1250, { title: 'gaming/idrupgrade:FRIENDS_16_TITLE', response: 'gaming/idrupgrade:FRIENDS_16_RESPONSE' }],
      [1500, { title: 'gaming/idrupgrade:FRIENDS_17_TITLE', response: 'gaming/idrupgrade:FRIENDS_17_RESPONSE' }],
      [2000, { title: 'gaming/idrupgrade:FRIENDS_18_TITLE', response: 'gaming/idrupgrade:FRIENDS_18_RESPONSE' }]
    ])
  },
  servers: {
    baseCost: 60,
    baseProfit: 30,
    upgrades: new Map([
      [1, { title: 'gaming/idrupgrade:SERVERS_1_TITLE', response: 'gaming/idrupgrade:SERVERS_1_RESPONSE' }],
      [25, { title: 'gaming/idrupgrade:SERVERS_2_TITLE', response: 'gaming/idrupgrade:SERVERS_2_RESPONSE' }],
      [50, { title: 'gaming/idrupgrade:SERVERS_3_TITLE', response: 'gaming/idrupgrade:SERVERS_3_RESPONSE' }],
      [75, { title: 'gaming/idrupgrade:SERVERS_4_TITLE', response: 'gaming/idrupgrade:SERVERS_4_RESPONSE' }],
      [100, { title: 'gaming/idrupgrade:SERVERS_5_TITLE', response: 'gaming/idrupgrade:SERVERS_5_RESPONSE' }],
      [150, { title: 'gaming/idrupgrade:SERVERS_6_TITLE', response: 'gaming/idrupgrade:SERVERS_6_RESPONSE' }],
      [200, { title: 'gaming/idrupgrade:SERVERS_7_TITLE', response: 'gaming/idrupgrade:SERVERS_7_RESPONSE' }],
      [300, { title: 'gaming/idrupgrade:SERVERS_8_TITLE', response: 'gaming/idrupgrade:SERVERS_8_RESPONSE' }],
      [400, { title: 'gaming/idrupgrade:SERVERS_9_TITLE', response: 'gaming/idrupgrade:SERVERS_9_RESPONSE' }],
      [500, { title: 'gaming/idrupgrade:SERVERS_10_TITLE', response: 'gaming/idrupgrade:SERVERS_10_RESPONSE' }],
      [600, { title: 'gaming/idrupgrade:SERVERS_11_TITLE', response: 'gaming/idrupgrade:SERVERS_11_RESPONSE' }],
      [700, { title: 'gaming/idrupgrade:SERVERS_12_TITLE', response: 'gaming/idrupgrade:SERVERS_12_RESPONSE' }],
      [800, { title: 'gaming/idrupgrade:SERVERS_13_TITLE', response: 'gaming/idrupgrade:SERVERS_13_RESPONSE' }],
      [900, { title: 'gaming/idrupgrade:SERVERS_14_TITLE', response: 'gaming/idrupgrade:SERVERS_14_RESPONSE' }],
      [1000, { title: 'gaming/idrupgrade:SERVERS_15_TITLE', response: 'gaming/idrupgrade:SERVERS_15_RESPONSE' }],
      [1250, { title: 'gaming/idrupgrade:SERVERS_16_TITLE', response: 'gaming/idrupgrade:SERVERS_16_RESPONSE' }],
      [1500, { title: 'gaming/idrupgrade:SERVERS_17_TITLE', response: 'gaming/idrupgrade:SERVERS_17_RESPONSE' }],
      [2000, { title: 'gaming/idrupgrade:SERVERS_18_TITLE', response: 'gaming/idrupgrade:SERVERS_18_RESPONSE' }]
    ])
  },
  channels: {
    baseCost: 720,
    baseProfit: 90,
    upgrades: new Map([
      [1, { title: 'gaming/idrupgrade:CHANNELS_1_TITLE', response: 'gaming/idrupgrade:CHANNELS_1_RESPONSE' }],
      [25, { title: 'gaming/idrupgrade:CHANNELS_2_TITLE', response: 'gaming/idrupgrade:CHANNELS_2_RESPONSE' }],
      [50, { title: 'gaming/idrupgrade:CHANNELS_3_TITLE', response: 'gaming/idrupgrade:CHANNELS_3_RESPONSE' }],
      [75, { title: 'gaming/idrupgrade:CHANNELS_4_TITLE', response: 'gaming/idrupgrade:CHANNELS_4_RESPONSE' }],
      [100, { title: 'gaming/idrupgrade:CHANNELS_5_TITLE', response: 'gaming/idrupgrade:CHANNELS_5_RESPONSE' }],
      [150, { title: 'gaming/idrupgrade:CHANNELS_6_TITLE', response: 'gaming/idrupgrade:CHANNELS_6_RESPONSE' }],
      [200, { title: 'gaming/idrupgrade:CHANNELS_7_TITLE', response: 'gaming/idrupgrade:CHANNELS_7_RESPONSE' }],
      [300, { title: 'gaming/idrupgrade:CHANNELS_8_TITLE', response: 'gaming/idrupgrade:CHANNELS_8_RESPONSE' }],
      [400, { title: 'gaming/idrupgrade:CHANNELS_9_TITLE', response: 'gaming/idrupgrade:CHANNELS_9_RESPONSE' }],
      [500, { title: 'gaming/idrupgrade:CHANNELS_10_TITLE', response: 'gaming/idrupgrade:CHANNELS_10_RESPONSE' }],
      [600, { title: 'gaming/idrupgrade:CHANNELS_11_TITLE', response: 'gaming/idrupgrade:CHANNELS_11_RESPONSE' }],
      [700, { title: 'gaming/idrupgrade:CHANNELS_12_TITLE', response: 'gaming/idrupgrade:CHANNELS_12_RESPONSE' }],
      [800, { title: 'gaming/idrupgrade:CHANNELS_13_TITLE', response: 'gaming/idrupgrade:CHANNELS_13_RESPONSE' }],
      [900, { title: 'gaming/idrupgrade:CHANNELS_14_TITLE', response: 'gaming/idrupgrade:CHANNELS_14_RESPONSE' }],
      [1000, { title: 'gaming/idrupgrade:CHANNELS_15_TITLE', response: 'gaming/idrupgrade:CHANNELS_15_RESPONSE' }],
      [1250, { title: 'gaming/idrupgrade:CHANNELS_16_TITLE', response: 'gaming/idrupgrade:CHANNELS_16_RESPONSE' }],
      [1500, { title: 'gaming/idrupgrade:CHANNELS_17_TITLE', response: 'gaming/idrupgrade:CHANNELS_17_RESPONSE' }],
      [2000, { title: 'gaming/idrupgrade:CHANNELS_18_TITLE', response: 'gaming/idrupgrade:CHANNELS_18_RESPONSE' }]
    ])
  },
  roles: {
    baseCost: 8640,
    baseProfit: 360,
    upgrades: new Map([
      [1, { title: 'gaming/idrupgrade:ROLES_1_TITLE', response: 'gaming/idrupgrade:ROLES_1_RESPONSE' }],
      [25, { title: 'gaming/idrupgrade:ROLES_2_TITLE', response: 'gaming/idrupgrade:ROLES_2_RESPONSE' }],
      [50, { title: 'gaming/idrupgrade:ROLES_3_TITLE', response: 'gaming/idrupgrade:ROLES_3_RESPONSE' }],
      [75, { title: 'gaming/idrupgrade:ROLES_4_TITLE', response: 'gaming/idrupgrade:ROLES_4_RESPONSE' }],
      [100, { title: 'gaming/idrupgrade:ROLES_5_TITLE', response: 'gaming/idrupgrade:ROLES_5_RESPONSE' }],
      [150, { title: 'gaming/idrupgrade:ROLES_6_TITLE', response: 'gaming/idrupgrade:ROLES_6_RESPONSE' }],
      [200, { title: 'gaming/idrupgrade:ROLES_7_TITLE', response: 'gaming/idrupgrade:ROLES_7_RESPONSE' }],
      [300, { title: 'gaming/idrupgrade:ROLES_8_TITLE', response: 'gaming/idrupgrade:ROLES_8_RESPONSE' }],
      [400, { title: 'gaming/idrupgrade:ROLES_9_TITLE', response: 'gaming/idrupgrade:ROLES_9_RESPONSE' }],
      [500, { title: 'gaming/idrupgrade:ROLES_10_TITLE', response: 'gaming/idrupgrade:ROLES_10_RESPONSE' }],
      [600, { title: 'gaming/idrupgrade:ROLES_11_TITLE', response: 'gaming/idrupgrade:ROLES_11_RESPONSE' }],
      [700, { title: 'gaming/idrupgrade:ROLES_12_TITLE', response: 'gaming/idrupgrade:ROLES_12_RESPONSE' }],
      [800, { title: 'gaming/idrupgrade:ROLES_13_TITLE', response: 'gaming/idrupgrade:ROLES_13_RESPONSE' }],
      [900, { title: 'gaming/idrupgrade:ROLES_14_TITLE', response: 'gaming/idrupgrade:ROLES_14_RESPONSE' }],
      [1000, { title: 'gaming/idrupgrade:ROLES_15_TITLE', response: 'gaming/idrupgrade:ROLES_15_RESPONSE' }],
      [1250, { title: 'gaming/idrupgrade:ROLES_16_TITLE', response: 'gaming/idrupgrade:ROLES_16_RESPONSE' }],
      [1500, { title: 'gaming/idrupgrade:ROLES_17_TITLE', response: 'gaming/idrupgrade:ROLES_17_RESPONSE' }],
      [2000, { title: 'gaming/idrupgrade:ROLES_18_TITLE', response: 'gaming/idrupgrade:ROLES_18_RESPONSE' }]
    ])
  },
  permissions: {
    baseCost: 103680,
    baseProfit: 2880,
    upgrades: new Map([
      [1, { title: 'gaming/idrupgrade:PERMS_1_TITLE', response: 'gaming/idrupgrade:PERMS_1_RESPONSE' }],
      [25, { title: 'gaming/idrupgrade:PERMS_2_TITLE', response: 'gaming/idrupgrade:PERMS_2_RESPONSE' }],
      [50, { title: 'gaming/idrupgrade:PERMS_3_TITLE', response: 'gaming/idrupgrade:PERMS_3_RESPONSE' }],
      [75, { title: 'gaming/idrupgrade:PERMS_4_TITLE', response: 'gaming/idrupgrade:PERMS_4_RESPONSE' }],
      [100, { title: 'gaming/idrupgrade:PERMS_5_TITLE', response: 'gaming/idrupgrade:PERMS_5_RESPONSE' }],
      [150, { title: 'gaming/idrupgrade:PERMS_6_TITLE', response: 'gaming/idrupgrade:PERMS_6_RESPONSE' }],
      [200, { title: 'gaming/idrupgrade:PERMS_7_TITLE', response: 'gaming/idrupgrade:PERMS_7_RESPONSE' }],
      [300, { title: 'gaming/idrupgrade:PERMS_8_TITLE', response: 'gaming/idrupgrade:PERMS_8_RESPONSE' }],
      [400, { title: 'gaming/idrupgrade:PERMS_9_TITLE', response: 'gaming/idrupgrade:PERMS_9_RESPONSE' }],
      [500, { title: 'gaming/idrupgrade:PERMS_10_TITLE', response: 'gaming/idrupgrade:PERMS_10_RESPONSE' }],
      [600, { title: 'gaming/idrupgrade:PERMS_11_TITLE', response: 'gaming/idrupgrade:PERMS_11_RESPONSE' }],
      [700, { title: 'gaming/idrupgrade:PERMS_12_TITLE', response: 'gaming/idrupgrade:PERMS_12_RESPONSE' }],
      [800, { title: 'gaming/idrupgrade:PERMS_13_TITLE', response: 'gaming/idrupgrade:PERMS_13_RESPONSE' }],
      [900, { title: 'gaming/idrupgrade:PERMS_14_TITLE', response: 'gaming/idrupgrade:PERMS_14_RESPONSE' }],
      [1000, { title: 'gaming/idrupgrade:PERMS_15_TITLE', response: 'gaming/idrupgrade:PERMS_15_RESPONSE' }],
      [1250, { title: 'gaming/idrupgrade:PERMS_16_TITLE', response: 'gaming/idrupgrade:PERMS_16_RESPONSE' }],
      [1500, { title: 'gaming/idrupgrade:PERMS_17_TITLE', response: 'gaming/idrupgrade:PERMS_17_RESPONSE' }],
      [2000, { title: 'gaming/idrupgrade:PERMS_18_TITLE', response: 'gaming/idrupgrade:PERMS_18_RESPONSE' }]
    ])
  },
  messages: {
    baseCost: 1244160,
    baseProfit: 6480,
    upgrades: new Map([
      [1, { title: 'gaming/idrupgrade:MESSAGES_1_TITLE', response: 'gaming/idrupgrade:MESSAGES_1_RESPONSE' }],
      [25, { title: 'gaming/idrupgrade:MESSAGES_2_TITLE', response: 'gaming/idrupgrade:MESSAGES_2_RESPONSE' }],
      [50, { title: 'gaming/idrupgrade:MESSAGES_3_TITLE', response: 'gaming/idrupgrade:MESSAGES_3_RESPONSE' }],
      [75, { title: 'gaming/idrupgrade:MESSAGES_4_TITLE', response: 'gaming/idrupgrade:MESSAGES_4_RESPONSE' }],
      [100, { title: 'gaming/idrupgrade:MESSAGES_5_TITLE', response: 'gaming/idrupgrade:MESSAGES_5_RESPONSE' }],
      [150, { title: 'gaming/idrupgrade:MESSAGES_6_TITLE', response: 'gaming/idrupgrade:MESSAGES_6_RESPONSE' }],
      [200, { title: 'gaming/idrupgrade:MESSAGES_7_TITLE', response: 'gaming/idrupgrade:MESSAGES_7_RESPONSE' }],
      [300, { title: 'gaming/idrupgrade:MESSAGES_8_TITLE', response: 'gaming/idrupgrade:MESSAGES_8_RESPONSE' }],
      [400, { title: 'gaming/idrupgrade:MESSAGES_9_TITLE', response: 'gaming/idrupgrade:MESSAGES_9_RESPONSE' }],
      [500, { title: 'gaming/idrupgrade:MESSAGES_10_TITLE', response: 'gaming/idrupgrade:MESSAGES_10_RESPONSE' }],
      [600, { title: 'gaming/idrupgrade:MESSAGES_11_TITLE', response: 'gaming/idrupgrade:MESSAGES_11_RESPONSE' }],
      [700, { title: 'gaming/idrupgrade:MESSAGES_12_TITLE', response: 'gaming/idrupgrade:MESSAGES_12_RESPONSE' }],
      [800, { title: 'gaming/idrupgrade:MESSAGES_13_TITLE', response: 'gaming/idrupgrade:MESSAGES_13_RESPONSE' }],
      [900, { title: 'gaming/idrupgrade:MESSAGES_14_TITLE', response: 'gaming/idrupgrade:MESSAGES_14_RESPONSE' }],
      [1000, { title: 'gaming/idrupgrade:MESSAGES_15_TITLE', response: 'gaming/idrupgrade:MESSAGES_15_RESPONSE' }],
      [1250, { title: 'gaming/idrupgrade:MESSAGES_16_TITLE', response: 'gaming/idrupgrade:MESSAGES_16_RESPONSE' }],
      [1500, { title: 'gaming/idrupgrade:MESSAGES_17_TITLE', response: 'gaming/idrupgrade:MESSAGES_17_RESPONSE' }],
      [2000, { title: 'gaming/idrupgrade:MESSAGES_18_TITLE', response: 'gaming/idrupgrade:MESSAGES_18_RESPONSE' }]
    ])
  },
  invites: {
    baseCost: 14929920,
    baseProfit: 19437,
    upgrades: new Map([
      [1, { title: 'gaming/idrupgrade:INVITES_1_TITLE', response: 'gaming/idrupgrade:INVITES_1_RESPONSE' }],
      [25, { title: 'gaming/idrupgrade:INVITES_2_TITLE', response: 'gaming/idrupgrade:INVITES_2_RESPONSE' }],
      [50, { title: 'gaming/idrupgrade:INVITES_3_TITLE', response: 'gaming/idrupgrade:INVITES_3_RESPONSE' }],
      [75, { title: 'gaming/idrupgrade:INVITES_4_TITLE', response: 'gaming/idrupgrade:INVITES_4_RESPONSE' }],
      [100, { title: 'gaming/idrupgrade:INVITES_5_TITLE', response: 'gaming/idrupgrade:INVITES_5_RESPONSE' }],
      [150, { title: 'gaming/idrupgrade:INVITES_6_TITLE', response: 'gaming/idrupgrade:INVITES_6_RESPONSE' }],
      [200, { title: 'gaming/idrupgrade:INVITES_7_TITLE', response: 'gaming/idrupgrade:INVITES_7_RESPONSE' }],
      [300, { title: 'gaming/idrupgrade:INVITES_8_TITLE', response: 'gaming/idrupgrade:INVITES_8_RESPONSE' }],
      [400, { title: 'gaming/idrupgrade:INVITES_9_TITLE', response: 'gaming/idrupgrade:INVITES_9_RESPONSE' }],
      [500, { title: 'gaming/idrupgrade:INVITES_10_TITLE', response: 'gaming/idrupgrade:INVITES_10_RESPONSE' }],
      [600, { title: 'gaming/idrupgrade:INVITES_11_TITLE', response: 'gaming/idrupgrade:INVITES_11_RESPONSE' }],
      [700, { title: 'gaming/idrupgrade:INVITES_12_TITLE', response: 'gaming/idrupgrade:INVITES_12_RESPONSE' }],
      [800, { title: 'gaming/idrupgrade:INVITES_13_TITLE', response: 'gaming/idrupgrade:INVITES_13_RESPONSE' }],
      [900, { title: 'gaming/idrupgrade:INVITES_14_TITLE', response: 'gaming/idrupgrade:INVITES_14_RESPONSE' }],
      [1000, { title: 'gaming/idrupgrade:INVITES_15_TITLE', response: 'gaming/idrupgrade:INVITES_15_RESPONSE' }],
      [1250, { title: 'gaming/idrupgrade:INVITES_16_TITLE', response: 'gaming/idrupgrade:INVITES_16_RESPONSE' }],
      [1500, { title: 'gaming/idrupgrade:INVITES_17_TITLE', response: 'gaming/idrupgrade:INVITES_17_RESPONSE' }],
      [2000, { title: 'gaming/idrupgrade:INVITES_18_TITLE', response: 'gaming/idrupgrade:INVITES_18_RESPONSE' }]
    ])
  },
  bots: {
    baseCost: 179159040,
    baseProfit: 58319,
    upgrades: new Map([
      [1, { title: 'gaming/idrupgrade:BOTS_1_TITLE', response: 'gaming/idrupgrade:BOTS_1_RESPONSE' }],
      [25, { title: 'gaming/idrupgrade:BOTS_2_TITLE', response: 'gaming/idrupgrade:BOTS_2_RESPONSE' }],
      [50, { title: 'gaming/idrupgrade:BOTS_3_TITLE', response: 'gaming/idrupgrade:BOTS_3_RESPONSE' }],
      [75, { title: 'gaming/idrupgrade:BOTS_4_TITLE', response: 'gaming/idrupgrade:BOTS_4_RESPONSE' }],
      [100, { title: 'gaming/idrupgrade:BOTS_5_TITLE', response: 'gaming/idrupgrade:BOTS_5_RESPONSE' }],
      [150, { title: 'gaming/idrupgrade:BOTS_6_TITLE', response: 'gaming/idrupgrade:BOTS_6_RESPONSE' }],
      [200, { title: 'gaming/idrupgrade:BOTS_7_TITLE', response: 'gaming/idrupgrade:BOTS_7_RESPONSE' }],
      [300, { title: 'gaming/idrupgrade:BOTS_8_TITLE', response: 'gaming/idrupgrade:BOTS_8_RESPONSE' }],
      [400, { title: 'gaming/idrupgrade:BOTS_9_TITLE', response: 'gaming/idrupgrade:BOTS_9_RESPONSE' }],
      [500, { title: 'gaming/idrupgrade:BOTS_10_TITLE', response: 'gaming/idrupgrade:BOTS_10_RESPONSE' }],
      [600, { title: 'gaming/idrupgrade:BOTS_11_TITLE', response: 'gaming/idrupgrade:BOTS_11_RESPONSE' }],
      [700, { title: 'gaming/idrupgrade:BOTS_12_TITLE', response: 'gaming/idrupgrade:BOTS_12_RESPONSE' }],
      [800, { title: 'gaming/idrupgrade:BOTS_13_TITLE', response: 'gaming/idrupgrade:BOTS_13_RESPONSE' }],
      [900, { title: 'gaming/idrupgrade:BOTS_14_TITLE', response: 'gaming/idrupgrade:BOTS_14_RESPONSE' }],
      [1000, { title: 'gaming/idrupgrade:BOTS_15_TITLE', response: 'gaming/idrupgrade:BOTS_15_RESPONSE' }],
      [1250, { title: 'gaming/idrupgrade:BOTS_16_TITLE', response: 'gaming/idrupgrade:BOTS_16_RESPONSE' }],
      [1500, { title: 'gaming/idrupgrade:BOTS_17_TITLE', response: 'gaming/idrupgrade:BOTS_17_RESPONSE' }],
      [2000, { title: 'gaming/idrupgrade:BOTS_18_TITLE', response: 'gaming/idrupgrade:BOTS_18_RESPONSE' }]
    ])
  },
  hypesquads: {
    baseCost: 2149908480,
    baseProfit: 175490,
    upgrades: new Map([
      [1, { title: 'gaming/idrupgrade:HYPESQUADS_1_TITLE', response: 'gaming/idrupgrade:HYPESQUADS_1_RESPONSE' }],
      [25, { title: 'gaming/idrupgrade:HYPESQUADS_2_TITLE', response: 'gaming/idrupgrade:HYPESQUADS_2_RESPONSE' }],
      [50, { title: 'gaming/idrupgrade:HYPESQUADS_3_TITLE', response: 'gaming/idrupgrade:HYPESQUADS_3_RESPONSE' }],
      [75, { title: 'gaming/idrupgrade:HYPESQUADS_4_TITLE', response: 'gaming/idrupgrade:HYPESQUADS_4_RESPONSE' }],
      [100, { title: 'gaming/idrupgrade:HYPESQUADS_5_TITLE', response: 'gaming/idrupgrade:HYPESQUADS_5_RESPONSE' }],
      [150, { title: 'gaming/idrupgrade:HYPESQUADS_6_TITLE', response: 'gaming/idrupgrade:HYPESQUADS_6_RESPONSE' }],
      [200, { title: 'gaming/idrupgrade:HYPESQUADS_7_TITLE', response: 'gaming/idrupgrade:HYPESQUADS_7_RESPONSE' }],
      [300, { title: 'gaming/idrupgrade:HYPESQUADS_8_TITLE', response: 'gaming/idrupgrade:HYPESQUADS_8_RESPONSE' }],
      [400, { title: 'gaming/idrupgrade:HYPESQUADS_9_TITLE', response: 'gaming/idrupgrade:HYPESQUADS_9_RESPONSE' }],
      [500, { title: 'gaming/idrupgrade:HYPESQUADS_10_TITLE', response: 'gaming/idrupgrade:HYPESQUADS_10_RESPONSE' }],
      [600, { title: 'gaming/idrupgrade:HYPESQUADS_11_TITLE', response: 'gaming/idrupgrade:HYPESQUADS_11_RESPONSE' }],
      [700, { title: 'gaming/idrupgrade:HYPESQUADS_12_TITLE', response: 'gaming/idrupgrade:HYPESQUADS_12_RESPONSE' }],
      [800, { title: 'gaming/idrupgrade:HYPESQUADS_13_TITLE', response: 'gaming/idrupgrade:HYPESQUADS_13_RESPONSE' }],
      [900, { title: 'gaming/idrupgrade:HYPESQUADS_14_TITLE', response: 'gaming/idrupgrade:HYPESQUADS_14_RESPONSE' }],
      [1000, { title: 'gaming/idrupgrade:HYPESQUADS_15_TITLE', response: 'gaming/idrupgrade:HYPESQUADS_15_RESPONSE' }],
      [1250, { title: 'gaming/idrupgrade:HYPESQUADS_16_TITLE', response: 'gaming/idrupgrade:HYPESQUADS_16_RESPONSE' }],
      [1500, { title: 'gaming/idrupgrade:HYPESQUADS_17_TITLE', response: 'gaming/idrupgrade:HYPESQUADS_17_RESPONSE' }],
      [2000, { title: 'gaming/idrupgrade:HYPESQUADS_18_TITLE', response: 'gaming/idrupgrade:HYPESQUADS_18_RESPONSE' }]
    ])
  },
  nitro: {
    baseCost: 25798901760,
    baseProfit: 1610667,
    upgrades: new Map([
      [1, { title: 'gaming/idrupgrade:NITRO_1_TITLE', response: 'gaming/idrupgrade:NITRO_1_RESPONSE' }],
      [25, { title: 'gaming/idrupgrade:NITRO_2_TITLE', response: 'gaming/idrupgrade:NITRO_2_RESPONSE' }],
      [50, { title: 'gaming/idrupgrade:NITRO_3_TITLE', response: 'gaming/idrupgrade:NITRO_3_RESPONSE' }],
      [75, { title: 'gaming/idrupgrade:NITRO_4_TITLE', response: 'gaming/idrupgrade:NITRO_4_RESPONSE' }],
      [100, { title: 'gaming/idrupgrade:NITRO_5_TITLE', response: 'gaming/idrupgrade:NITRO_5_RESPONSE' }],
      [150, { title: 'gaming/idrupgrade:NITRO_6_TITLE', response: 'gaming/idrupgrade:NITRO_6_RESPONSE' }],
      [200, { title: 'gaming/idrupgrade:NITRO_7_TITLE', response: 'gaming/idrupgrade:NITRO_7_RESPONSE' }],
      [300, { title: 'gaming/idrupgrade:NITRO_8_TITLE', response: 'gaming/idrupgrade:NITRO_8_RESPONSE' }],
      [400, { title: 'gaming/idrupgrade:NITRO_9_TITLE', response: 'gaming/idrupgrade:NITRO_9_RESPONSE' }],
      [500, { title: 'gaming/idrupgrade:NITRO_10_TITLE', response: 'gaming/idrupgrade:NITRO_10_RESPONSE' }],
      [600, { title: 'gaming/idrupgrade:NITRO_11_TITLE', response: 'gaming/idrupgrade:NITRO_11_RESPONSE' }],
      [700, { title: 'gaming/idrupgrade:NITRO_12_TITLE', response: 'gaming/idrupgrade:NITRO_12_RESPONSE' }],
      [800, { title: 'gaming/idrupgrade:NITRO_13_TITLE', response: 'gaming/idrupgrade:NITRO_13_RESPONSE' }],
      [900, { title: 'gaming/idrupgrade:NITRO_14_TITLE', response: 'gaming/idrupgrade:NITRO_14_RESPONSE' }],
      [1000, { title: 'gaming/idrupgrade:NITRO_15_TITLE', response: 'gaming/idrupgrade:NITRO_15_RESPONSE' }],
      [1250, { title: 'gaming/idrupgrade:NITRO_16_TITLE', response: 'gaming/idrupgrade:NITRO_16_RESPONSE' }],
      [1500, { title: 'gaming/idrupgrade:NITRO_17_TITLE', response: 'gaming/idrupgrade:NITRO_17_RESPONSE' }],
      [2000, { title: 'gaming/idrupgrade:NITRO_18_TITLE', response: 'gaming/idrupgrade:NITRO_18_RESPONSE' }]
    ])
  }
}
